@ReturnValuesAreNonnullByDefault
@FieldsAreNonnullByDefault
@ParametersAreNonnullByDefault
package corewar.stadium.memory;

import corewar.shared.FieldsAreNonnullByDefault;
import corewar.shared.ReturnValuesAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;